# Generated by Django 6.0.6 on 2026-06-03 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=10, unique=True, verbose_name='Номер заказа')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон клиента')),
                ('details', models.TextField(verbose_name='Состав заказа')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
        ),
    ]
